name: Draft Label Switcher (title)

on:
  pull_request:
    types: [opened, ready_for_review, converted_to_draft]

jobs:
  draft_label_switcher:
    runs-on: ubuntu-latest
    name: Draft Label Switcher (name in text)
    steps:
    - name: label swapping
      uses: jinmayamashita/ready-for-review@1.0.0
      with:
        in-progress-label: '++draft PR++'
        ready-for-review-label: ''
        repo-token: ${{ secrets.GITHUB_TOKEN }}
