name: label-automation-on-link

# add in Bearbeitung label when issue linked to pull request

on:
  issues:
    types: [connected, connect]

jobs:
  automate-labels:
    runs-on: ubuntu-latest
    name: automate labels for issues linked to PR
    steps:
      - name: add "in Bearbeitung" label
        uses: upinetree/labeler@fix-pull-request-param
        with:
          add-labels: "-- in Bearbeitung"
      