name: label-automation-on-draft

on:
  pull_request:
    types: [opened, ready_for_review, converted_to_draft]

jobs:
  automate-labels:
    runs-on: ubuntu-latest
    name: automate labels for draft PR (name in text)
    steps:
      - name: add draft label
        uses: upinetree/labeler@fix-pull-request-param
        if: github.event.action == 'converted_to_draft'
        with:
          add-labels: "++draft PR++"
      - name: remove draft label
        uses: upinetree/labeler@fix-pull-request-param
        if: github.event.action == 'ready_for_review'
        with:
          remove-labels: "++draft PR++"

